name: Deploy JEDUG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            export PATH="/home/ryandotcodotid/.nvm/versions/node/v24.14.0/bin:$PATH"
            PM2_BIN="/home/ryandotcodotid/.nvm/versions/node/v24.14.0/bin/pm2"

            cd /home/ryandotcodotid/projects/jedug_v2

            echo "Pull latest code"
            git remote -v
            git fetch origin || (sleep 5 && git fetch origin)
            git reset --hard origin/main

            echo "Build backend"
            cd backend
            go mod tidy
            mkdir -p bin
            go build -o bin/jedug-api ./cmd/api
            "$PM2_BIN" restart jedug-api --update-env

            echo "Build frontend"
            cd ../frontend
            npm ci
            npm run build
            "$PM2_BIN" restart jedug-web --update-env

            "$PM2_BIN" save

            echo "Deploy selesai"
